### PR TITLE
Comment out 'install' lines in collada-dom' CMakeLists.txt, because

### PR DESCRIPTION
**Pull request by oikumene**
we do not really use what is 'installed', but use what is there before installing.
This should fix the build on Ubuntu.

### CODE REVIEW

**Comment by K3ysin** [comment]
When this get merged with main that I can update it that i can re-try the build?

**Comment by oikumene** [comment]
Yes. Sorry, wait for some time.

**Comment by erikkundiman** [comment]
Thank you so much @oikumene 
@K3ysin I have merged it to main, so you can pull and try it, now.. please, thank you.
I can't check it myself right away, however, but I should be available soon.
Thanks!

**Comment by K3ysin** [comment]
> Thank you so much @oikumene @K3ysin I have merged it to main, so you can pull and try it, now.. please, thank you. I can't check it myself right away, however, but I should be available soon. Thanks!

I get now this error while I make it: In file included from /home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeIOPluginCommon.cpp:18:
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/include/dae/daeZAEUncompressHandler.h:12:10: fatal error: unzip.h: Datei oder Verzeichnis nicht gefunden
   12 | #include <unzip.h>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [llprimitive/colladadom/src/1.4/CMakeFiles/collada14dom.dir/build.make:216: llprimitive/colladadom/src/1.4/CMakeFiles/collada14dom.dir/home/keysin/Megaphit_Build/3p-colladadom-2.3-r7/src/dae/daeIOPluginCommon.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1113: llprimitive/colladadom/src/1.4/CMakeFiles/collada14dom.dir/all] Fehler 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …

**Comment by oikumene** [comment]
@K3ysin do you have minizip installed? If so, what ```pkg-config --cflags minizip``` returns?

**Comment by erikkundiman** [comment]
@K3ysin I forgot to add 2 packages that need to be installed to the documentation since the new method.

sudo apt install libminizip-dev libpcre3-dev

Thank you

**Comment by K3ysin** [comment]
> @K3ysin I forgot to add 2 packages that need to be installed to the documentation since the new method.
> 
> sudo apt install libminizip-dev libpcre3-dev
> 
> Thank you

Thanks! Will install it!

**Comment by K3ysin** [comment]
In file included from /home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeIOPluginCommon.cpp:18:
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/include/dae/daeZAEUncompressHandler.h:13:10: fatal error: libxml/xmlreader.h: Datei oder Verzeichnis nicht gefunden
   13 | #include <libxml/xmlreader.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
New error I get.

**Comment by erikkundiman** [comment]
@K3ysin Do you have libxml2-dev installed?

**Comment by K3ysin** [comment]
Now I get this error:
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/modules/LIBXMLPlugin/daeLIBXMLPlugin.cpp:312:31: error: argument 1 null where non-null expected [-Werror=nonnull]
  312 |                         fclose(rawFile);
      |                         ~~~~~~^~~~~~~~~
/usr/include/stdio.h:184:12: note: in a call to function ‘int fclose(FILE*)’ declared ‘nonnull’
  184 | extern int fclose (FILE *__stream) __nonnull ((1));
      |            ^~~~~~
cc1plus: all warnings being treated as errors

**Comment by erikkundiman** [comment]
Try to add "-Wno-nonnull" to patches/colladadom-2.3-r7.patch line60, separate with a space

**Comment by K3ysin** [comment]
> Try to add "-Wno-nonnull" to patches/colladadom-2.3-r7.patch line60, separate with a space

But it is not recommend to do that, you should be pedantic and treat warnings as error. Else a null reference exception may occur, but I will do it.

**Comment by K3ysin** [comment]
Good. Where should I add it? This patch file is big.

**Comment by erikkundiman** [comment]
> > Try to add "-Wno-nonnull" to patches/colladadom-2.3-r7.patch line60, separate with a space
> 
> But it is not recommend to do that, you should be pedantic and treat warnings as error. Else a null reference exception may occur, but I will do it.

Sure, if someone wants to fix it, it's always open for contribution 😄  Otherwise, I haven't got the time yet (or ever 😛 ) 



> Good. Where should I add it? This patch file is big.

line 60

**Comment by K3ysin** [comment]
Now after that is fixed I get this error: /home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeRawResolver.cpp: In member function ‘virtual daeElement* daeRawResolver::resolveElement(const daeURI&)’:
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeRawResolver.cpp:89:30: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   89 |                         fread( &val, sizeof(daeInt), 1, rawFile );
      |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeRawResolver.cpp:98:30: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   98 |                         fread( &val, sizeof(daeFloat), 1, rawFile );
      |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by erikkundiman** [comment]
line 60 should already contain the -Wno- for it

**Comment by K3ysin** [comment]
> line 60 should already contain the -Wno- for it

No clue really. Maybe it is another command to treat this as warning?

**Comment by erikkundiman** [comment]
Ohh..  I think it should be "-Wno-unused-result" instead of "-Wno-error=unused-result"

**Comment by K3ysin** [comment]
Now I get this error: /home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeRawResolver.cpp: In member function ‘virtual daeElement* daeRawResolver::resolveElement(const daeURI&)’:
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeRawResolver.cpp:89:30: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   89 |                         fread( &val, sizeof(daeInt), 1, rawFile );
      |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/keysin/Megaphit Build/3p-colladadom-2.3-r7/src/dae/daeRawResolver.cpp:98:30: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   98 |                         fread( &val, sizeof(daeFloat), 1, rawFile );
      |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unused-value -Wno-nonnull’ may have been intended to silence earlier diagnostics

**Comment by K3ysin** [comment]
I try to build it with "-Wall" that is extremely unsafe but that will fix it.

**Comment by K3ysin** [comment]
Sorry my fault I mean -Werror

**Comment by K3ysin** [comment]
> Sorry my fault I mean -Werror

not it tells me I have also to combine that with unused result, but how can I combine that?

**Comment by erikkundiman** [comment]
all in line 60, each in quotes, separated by spaces

**Comment by oikumene** [comment]
In these changes, I dealt a third party software collada-dom as a submodule. Now, we are seeing the downside of it that the options for the viewer are also applied to collada-dom. As we do not have enough time to also develop collada-dom, I thought I should just add the cancellation of 'strong' options, but it is not enough. I will come back with a patch that works with these options. The options you are adding are '-Werror -Wall' or are there more?

**Comment by oikumene** [comment]
As we will not check any warnings with collada-dom, just replacing -Wno-error=unused-result to -Wno-error may suffice. I am testing it locally.

**Comment by K3ysin** [comment]
> In these changes, I dealt a third party software collada-dom as a submodule. Now, we are seeing the downside of it that the options for the viewer are also applied to collada-dom. As we do not have enough time to also develop collada-dom, I thought I should just add the cancellation of 'strong' options, but it is not enough. I will come back with a patch that works with these options. The options you are adding are '-Werror -Wall' or are there more?

May you tell me for what collada is for?

**Comment by oikumene** [comment]
Collada-DOM is a library that reads and writes 2D, 3D and physics models. We use it as a third party library like minizip it uses. Unfortunatelly, the collada-dom library present as a package in Ubuntu or other distributions is a version that does not support the format that Second Life uses. So, we need to build the version that we want to use by ourselves. But still, it is not the core viewer code.

Please replace the line 60 of the patch to the line below. It should skip all warnings in the build of collada-dom. (It does not affect other part of the viewer code build).

```
+        "-Wno-error"
```

**Pull request merged**
